require_relative 'root'
require_relative 'person'
require_relative 'genre'
require_relative 'song'
require_relative 'vote'
require_relative 'company'
require_relative 'prize'
require_relative 'wish'
require_relative 'winner'
require_relative 'default' # must be last!